// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseMicroservices.Models;

#nullable disable

namespace PurchaseMicroservices.Migrations
{
    [DbContext(typeof(PurchaseDBContext))]
    [Migration("20260425145033_updateportdata")]
    partial class updateportdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PurchaseMicroservices.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityPurchased")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            PurchaseId = 1,
                            EmailId = "test1@gmail.com",
                            ProductId = "P001",
                            QuantityPurchased = 2,
                            TotalPrice = 19.98m
                        },
                        new
                        {
                            PurchaseId = 2,
                            EmailId = "test2@gmail.com",
                            ProductId = "P002",
                            QuantityPurchased = 1,
                            TotalPrice = 9.99m
                        },
                        new
                        {
                            PurchaseId = 3,
                            EmailId = "test3@gmail.com",
                            ProductId = "P003",
                            QuantityPurchased = 3,
                            TotalPrice = 29.97m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
