// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserMicroservices.Models;

#nullable disable

namespace UserMicroservices.Migrations
{
    [DbContext(typeof(UserDBContext))]
    [Migration("20260426064355_usermigrate")]
    partial class usermigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserMicroservices.Models.User", b =>
                {
                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmailId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            EmailId = "Franken@gmail.com",
                            Address = "Texas, USA",
                            DateOfBirth = new DateTime(1978, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "M",
                            RoleName = "Admin",
                            UserPassword = "Franken@785"
                        },
                        new
                        {
                            EmailId = "SamRocks@gmail.com",
                            Address = "Denver, USA",
                            DateOfBirth = new DateTime(1986, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "M",
                            RoleName = "User",
                            UserPassword = "Sam@564"
                        },
                        new
                        {
                            EmailId = "PaulGrey@gmail.com",
                            Address = "Denver, USA",
                            DateOfBirth = new DateTime(1993, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "M",
                            RoleName = "User",
                            UserPassword = "Paul@123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
