// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductMicroservices.Models;

#nullable disable

namespace ProductMicroservices.Migrations
{
    [DbContext(typeof(ProductDBContext))]
    [Migration("20260216135433_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductMicroservices.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "P001",
                            CategoryId = (byte)1,
                            Price = 999.99m,
                            ProductName = "Laptop",
                            QuantityAvailable = 10
                        },
                        new
                        {
                            ProductId = "P002",
                            CategoryId = (byte)1,
                            Price = 499.99m,
                            ProductName = "Smartphone",
                            QuantityAvailable = 20
                        },
                        new
                        {
                            ProductId = "P003",
                            CategoryId = (byte)2,
                            Price = 199.99m,
                            ProductName = "Headphones",
                            QuantityAvailable = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
