// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductMicroservices.Models;

#nullable disable

namespace ProductMicroservices.Migrations
{
    [DbContext(typeof(ProductDBContext))]
    partial class ProductDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductMicroservices.Models.Category", b =>
                {
                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = (byte)1,
                            CategoryName = "Motors"
                        },
                        new
                        {
                            CategoryId = (byte)2,
                            CategoryName = "Arts"
                        },
                        new
                        {
                            CategoryId = (byte)3,
                            CategoryName = "Furniture"
                        });
                });

            modelBuilder.Entity("ProductMicroservices.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = "P101",
                            CategoryId = (byte)1,
                            Price = 18000000m,
                            ProductName = "Lamborghini Gallardo Spyder",
                            QuantityAvailable = 10
                        },
                        new
                        {
                            ProductId = "P102",
                            CategoryId = (byte)1,
                            Price = 700000m,
                            ProductName = "Harley Davidson Iron 883",
                            QuantityAvailable = 10
                        },
                        new
                        {
                            ProductId = "P103",
                            CategoryId = (byte)2,
                            Price = 2056m,
                            ProductName = "Abstract Hand painted Oil Painting on Canvas",
                            QuantityAvailable = 200
                        },
                        new
                        {
                            ProductId = "P104",
                            CategoryId = (byte)2,
                            Price = 9000m,
                            ProductName = "Marble Elephants statue",
                            QuantityAvailable = 100
                        },
                        new
                        {
                            ProductId = "P105",
                            CategoryId = (byte)3,
                            Price = 15000m,
                            ProductName = "Dining Table",
                            QuantityAvailable = 50
                        });
                });

            modelBuilder.Entity("ProductMicroservices.Models.Product", b =>
                {
                    b.HasOne("ProductMicroservices.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductMicroservices.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
