// <auto-generated />
using CategoryMicroservices.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CategoryMicroservices.Migrations
{
    [DbContext(typeof(CategoryDBContext))]
    partial class CategoryDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CategoryMicroservices.Models.Category", b =>
                {
                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = (byte)1,
                            CategoryName = "Motors"
                        },
                        new
                        {
                            CategoryId = (byte)2,
                            CategoryName = "Arts"
                        },
                        new
                        {
                            CategoryId = (byte)3,
                            CategoryName = "Furniture"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
